spring:
  datasource:
    url: jdbc:mysql://172.18.49.5:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
   db-config:
      id-type: auto
#   db-config:
#   id-type: auto
#   
server:
  port: 11000